"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _dashboard from './dashboard.bones.json'
import _branch_detail from './branch-detail.bones.json'
import _admissions_funnel from './admissions-funnel.bones.json'
import _operational_list from './operational-list.bones.json'
import _profile_detail from './profile-detail.bones.json'
import _institute_profile from './institute-profile.bones.json'
import _parents_directory from './parents-directory.bones.json'
import _timetable_route from './timetable-route.bones.json'
import _operational_record_detail from './operational-record-detail.bones.json'
import _timetable_saved_list from './timetable-saved-list.bones.json'
import _fee_structure_page from './fee-structure-page.bones.json'
import _table_people from './table-people.bones.json'
import _table_staff_members from './table-staff-members.bones.json'
import _table_students from './table-students.bones.json'
import _table_roles from './table-roles.bones.json'
import _table_role_assignments from './table-role-assignments.bones.json'
import _table_enquiries from './table-enquiries.bones.json'
import _table_scheduled_events from './table-scheduled-events.bones.json'
import _table_fee_invoices from './table-fee-invoices.bones.json'
import _academics_operations from './academics-operations.bones.json'
import _academic_structure_subjects from './academic-structure-subjects.bones.json'
import _attendance_mark_roster from './attendance-mark-roster.bones.json'
import _attendance_overview_charts from './attendance-overview-charts.bones.json'
import _attendance_overview_calendar from './attendance-overview-calendar.bones.json'
import _attendance_reports_analytics from './attendance-reports-analytics.bones.json'
import _attendance_leave_approvals from './attendance-leave-approvals.bones.json'
import _timetable_teachers from './timetable-teachers.bones.json'
import _timetable_structure from './timetable-structure.bones.json'
import _timetable_assignments from './timetable-assignments.bones.json'
import _timetable_import from './timetable-import.bones.json'
import _timetable_timetable from './timetable-timetable.bones.json'
import _timetable_saved_view from './timetable-saved-view.bones.json'

registerBones({
  "dashboard": _dashboard,
  "branch-detail": _branch_detail,
  "admissions-funnel": _admissions_funnel,
  "operational-list": _operational_list,
  "profile-detail": _profile_detail,
  "institute-profile": _institute_profile,
  "parents-directory": _parents_directory,
  "timetable-route": _timetable_route,
  "operational-record-detail": _operational_record_detail,
  "timetable-saved-list": _timetable_saved_list,
  "fee-structure-page": _fee_structure_page,
  "table-people": _table_people,
  "table-staff-members": _table_staff_members,
  "table-students": _table_students,
  "table-roles": _table_roles,
  "table-role-assignments": _table_role_assignments,
  "table-enquiries": _table_enquiries,
  "table-scheduled-events": _table_scheduled_events,
  "table-fee-invoices": _table_fee_invoices,
  "academics-operations": _academics_operations,
  "academic-structure-subjects": _academic_structure_subjects,
  "attendance-mark-roster": _attendance_mark_roster,
  "attendance-overview-charts": _attendance_overview_charts,
  "attendance-overview-calendar": _attendance_overview_calendar,
  "attendance-reports-analytics": _attendance_reports_analytics,
  "attendance-leave-approvals": _attendance_leave_approvals,
  "timetable-teachers": _timetable_teachers,
  "timetable-structure": _timetable_structure,
  "timetable-assignments": _timetable_assignments,
  "timetable-import": _timetable_import,
  "timetable-timetable": _timetable_timetable,
  "timetable-saved-view": _timetable_saved_view,
})
