export const genericScreenIds = [
  'BR2', 'ST2', 'ST3', 'SD2', 'SD3', 'AD3', 'AD4', 'AD5', 'AD6',
  'AC3', 'AC4', 'AC5', 'AC6', 'AC7', 'AT2', 'AT3', 'FN1', 'FN3',
  'FN4', 'CM1', 'CM2', 'TT1', 'TT2', 'RG1', 'RG2', 'RG3', 'RG4',
  'RG5', 'RG6', 'RA1', 'RA2', 'AO1', 'AO2', 'AO3', 'SE2', 'SE3', 'SE4',
  'SE5', 'AL1', 'NT1', 'PR1', 'HP1',
] as const

export type GenericScreenId = (typeof genericScreenIds)[number]
export type WorkflowFieldType =
  | 'text' | 'email' | 'number' | 'date' | 'datetime'
  | 'select' | 'textarea' | 'boolean'

export interface WorkflowField {
  readonly key: string
  readonly label: string
  readonly type: WorkflowFieldType
  readonly required: boolean
  readonly options?: readonly string[]
  readonly hint?: string
}

interface WorkflowBase {
  readonly id: GenericScreenId
  readonly purpose: string
  readonly description: string
  readonly recordNoun: string
  readonly tabs: readonly string[]
  readonly segments: readonly string[]
  readonly statusChoices: readonly string[]
  readonly fields: readonly WorkflowField[]
}

export type ScreenWorkflow = WorkflowBase & (
  | { readonly readOnly: true; readonly primaryAction: null }
  | { readonly readOnly: false; readonly primaryAction: string }
)

type FieldInput = Omit<WorkflowField, 'required'> & { readonly required?: boolean }

const field = (definition: FieldInput): WorkflowField => ({
  required: false,
  ...definition,
})

const mutable = (workflow: Omit<WorkflowBase, 'id'> & { primaryAction: string }) => ({
  ...workflow,
  readOnly: false,
} as const)

const readOnly = (workflow: Omit<WorkflowBase, 'id'>) => ({
  ...workflow,
  primaryAction: null,
  readOnly: true,
} as const)

export const screenWorkflows = {
  BR2: mutable({
    purpose: 'Create, review, and maintain a branch profile and its permitted local overrides.',
    description: 'Branch details with linked staff and class summaries plus institute-default overrides.',
    primaryAction: 'Save Changes', recordNoun: 'branch',
    tabs: ['Details', 'Staff', 'Classes & Sections', 'Overrides'], segments: [],
    statusChoices: ['Active', 'Inactive'],
    fields: [
      field({ key: 'name', label: 'Branch name', type: 'text', required: true }),
      field({ key: 'code', label: 'Branch code', type: 'text', required: true }),
      field({ key: 'address', label: 'Address', type: 'textarea', required: true }),
      field({ key: 'phone', label: 'Phone', type: 'text', required: true }),
      field({ key: 'email', label: 'Email', type: 'email', required: true }),
      field({ key: 'branchAdmin', label: 'Branch administrator', type: 'select', options: ['Unassigned', 'Select eligible staff'], hint: 'The selected staff member must have branch-scoped administration access.' }),
      field({ key: 'timezone', label: 'Timezone', type: 'select', required: true, options: ['Asia/Kolkata', 'Asia/Dubai', 'UTC'] }),
      field({ key: 'latitude', label: 'Latitude', type: 'number' }),
      field({ key: 'longitude', label: 'Longitude', type: 'number' }),
      field({ key: 'maxStrength', label: 'Default maximum class strength', type: 'number' }),
      field({ key: 'isHeadOffice', label: 'Set as head office', type: 'boolean' }),
      field({ key: 'allowLocalCalendar', label: 'Allow local holiday calendar', type: 'boolean', hint: 'When off, the institute calendar remains authoritative.' }),
    ],
  }),
  ST2: mutable({
    purpose: 'Maintain a staff profile and the role assignments that control access.',
    description: 'Staff identity, employment, role scope, teaching assignments, attendance, and leave history.',
    primaryAction: 'Save Changes', recordNoun: 'staff member',
    tabs: ['Profile', 'Role Assignments', 'Classes Assigned', 'Attendance & Leave'], segments: [],
    statusChoices: ['Active', 'Inactive'],
    fields: [
      field({ key: 'name', label: 'Full name', type: 'text', required: true }),
      field({ key: 'employeeCode', label: 'Employee code', type: 'text', required: true }),
      field({ key: 'phone', label: 'Phone', type: 'text', required: true }),
      field({ key: 'email', label: 'Email', type: 'email', required: true }),
      field({ key: 'designation', label: 'Designation', type: 'text', required: true }),
      field({ key: 'joiningDate', label: 'Joining date', type: 'date', required: true }),
      field({ key: 'role', label: 'Role', type: 'select', options: ['Teacher', 'Branch Admin', 'Institute Admin', 'Custom role'], hint: 'Only roles whose permissions you hold can be assigned.' }),
      field({ key: 'roleScope', label: 'Role scope', type: 'select', options: ['Institute-wide', 'Specific branch'] }),
      field({ key: 'roleExpiry', label: 'Role expiry', type: 'date' }),
      field({ key: 'documentReference', label: 'Employment document reference', type: 'text', hint: 'Reference for contract or identity-proof uploads.' }),
    ],
  }),
  ST3: mutable({
    purpose: 'Review and decide staff leave applications.',
    description: 'Branch-scoped approval queue with complete reasons, review notes, and bulk approval.',
    primaryAction: 'Approve / Reject', recordNoun: 'leave request',
    tabs: ['Pending', 'Approved', 'Rejected'], segments: [],
    statusChoices: ['Pending', 'Approved', 'Rejected'],
    fields: [
      field({ key: 'staffMember', label: 'Staff member', type: 'select', required: true, options: ['Select staff member'] }),
      field({ key: 'startDate', label: 'Start date', type: 'date', required: true }),
      field({ key: 'endDate', label: 'End date', type: 'date', required: true }),
      field({ key: 'reason', label: 'Leave reason', type: 'textarea', required: true }),
      field({ key: 'decision', label: 'Decision', type: 'select', required: true, options: ['Approved', 'Rejected'] }),
      field({ key: 'reviewNote', label: 'Review note', type: 'textarea', hint: 'Required when rejecting a request.' }),
    ],
  }),
  SD2: mutable({
    purpose: 'Maintain the complete, durable record for one student.',
    description: 'Student identity, family links, enrollment, attendance, academics, recognition, fees, documents, and consent.',
    primaryAction: 'Save Changes', recordNoun: 'student',
    tabs: ['Profile', 'Family', 'Enrollment History', 'Attendance', 'Academics', 'Points & Batches', 'Fees', 'Documents', 'Consent'], segments: [],
    statusChoices: ['Active', 'Withdrawn'],
    fields: [
      field({ key: 'name', label: 'Student name', type: 'text', required: true }),
      field({ key: 'admissionNumber', label: 'Admission number', type: 'text', required: true }),
      field({ key: 'dateOfBirth', label: 'Date of birth', type: 'date', required: true }),
      field({ key: 'gender', label: 'Gender', type: 'select', options: ['Female', 'Male', 'Non-binary', 'Prefer not to say'] }),
      field({ key: 'bloodGroup', label: 'Blood group', type: 'select', options: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Unknown'] }),
      field({ key: 'medicalNotes', label: 'Allergies and medical notes', type: 'textarea' }),
      field({ key: 'address', label: 'Address', type: 'textarea', required: true }),
      field({ key: 'emergencyContact', label: 'Emergency contact', type: 'text', required: true }),
      field({ key: 'classSection', label: 'Class and section', type: 'select', required: true, options: ['Select class-section'] }),
      field({ key: 'rollNumber', label: 'Roll number', type: 'text' }),
      field({ key: 'guardian', label: 'Parent or guardian', type: 'select', options: ['Search existing parent', 'Create new parent'] }),
      field({ key: 'withdrawalDate', label: 'Withdrawal date', type: 'date' }),
      field({ key: 'withdrawalReason', label: 'Withdrawal reason', type: 'textarea' }),
    ],
  }),
  SD3: mutable({
    purpose: 'Import student rosters and generate branded ID cards in bulk.',
    description: 'A validated import wizard alongside class- and section-scoped ID-card batch generation.',
    primaryAction: 'Import', recordNoun: 'student import', tabs: [],
    segments: ['Import Students', 'Generate ID Cards'], statusChoices: ['Draft', 'Validating', 'Ready', 'Partially Imported', 'Imported', 'Failed'],
    fields: [
      field({ key: 'fileReference', label: 'Roster file', type: 'text', required: true, hint: 'Upload an Excel or CSV file based on the current template.' }),
      field({ key: 'headerRow', label: 'Header row', type: 'number', required: true }),
      field({ key: 'duplicateHandling', label: 'Duplicate admission numbers', type: 'select', required: true, options: ['Reject duplicate rows', 'Exclude duplicate rows'] }),
      field({ key: 'branch', label: 'Target branch', type: 'select', required: true, options: ['Select branch'] }),
      field({ key: 'studentSelection', label: 'ID-card student selection', type: 'select', options: ['Full roster', 'By class', 'By section'] }),
      field({ key: 'classSection', label: 'Class or section', type: 'select', options: ['Select class or section'] }),
      field({ key: 'includeQrCode', label: 'Include QR code', type: 'boolean' }),
    ],
  }),
  AD3: mutable({
    purpose: 'Progress a prospective family from enquiry through enrollment without losing history.',
    description: 'CRM detail with application, appointments, payments, and communication history.',
    primaryAction: 'Move to Next Stage', recordNoun: 'enquiry',
    tabs: ['Overview', 'Application', 'Visits & Tests', 'Payments', 'Communication Log'], segments: [],
    statusChoices: ['Enquiry', 'Contacted', 'Visit Scheduled', 'Applied', 'Entrance Test', 'Offered', 'Enrolled', 'Lost'],
    fields: [
      field({ key: 'parentName', label: 'Parent name', type: 'text', required: true }),
      field({ key: 'childName', label: 'Child name', type: 'text', required: true }),
      field({ key: 'phone', label: 'Phone', type: 'text', required: true }),
      field({ key: 'email', label: 'Email', type: 'email' }),
      field({ key: 'grade', label: 'Grade interested in', type: 'select', required: true, options: ['Select grade'] }),
      field({ key: 'source', label: 'Source', type: 'select', required: true, options: ['Website', 'Ads', 'Walk-in', 'Referral', 'Phone'] }),
      field({ key: 'leadScore', label: 'Lead score', type: 'select', options: ['Hot', 'Warm', 'Cold'] }),
      field({ key: 'counselor', label: 'Assigned counselor', type: 'select', options: ['Unassigned', 'Select counselor'] }),
      field({ key: 'note', label: 'Add note', type: 'textarea' }),
      field({ key: 'lostReason', label: 'Lost reason', type: 'select', options: ['Budget', 'Chose another school', 'No response', 'Location', 'Other'] }),
    ],
  }),
  AD4: mutable({
    purpose: 'Design and publish the public admission application form without code.',
    description: 'Field palette, live parent preview, validation settings, and application-fee configuration.',
    primaryAction: 'Publish Changes', recordNoun: 'application form', tabs: [], segments: ['Builder', 'Parent Preview'],
    statusChoices: ['Draft', 'Published'],
    fields: [
      field({ key: 'formName', label: 'Form name', type: 'text', required: true }),
      field({ key: 'fieldType', label: 'Field type', type: 'select', required: true, options: ['Text', 'Dropdown', 'Date', 'File upload', 'Payment'] }),
      field({ key: 'fieldLabel', label: 'Field label', type: 'text', required: true }),
      field({ key: 'fieldRequired', label: 'Required field', type: 'boolean' }),
      field({ key: 'validationRule', label: 'Validation rule', type: 'text' }),
      field({ key: 'applicationFee', label: 'Application fee', type: 'number' }),
      field({ key: 'paymentGateway', label: 'Payment gateway', type: 'select', options: ['None', 'Configured gateway'] }),
    ],
  }),
  AD5: mutable({
    purpose: 'Configure appointment availability and book campus visits or entrance tests.',
    description: 'Recurring slot templates and manual family bookings shown in a day or week calendar.',
    primaryAction: 'Create Slot Template', recordNoun: 'appointment slot', tabs: [], segments: ['Week', 'Day'],
    statusChoices: ['Available', 'Fully Booked', 'Waitlisted', 'Completed', 'Cancelled'],
    fields: [
      field({ key: 'appointmentType', label: 'Appointment type', type: 'select', required: true, options: ['Campus visit', 'Entrance test'] }),
      field({ key: 'startsAt', label: 'Starts at', type: 'datetime', required: true }),
      field({ key: 'durationMinutes', label: 'Duration in minutes', type: 'number', required: true }),
      field({ key: 'capacity', label: 'Family capacity', type: 'number', required: true }),
      field({ key: 'recurrence', label: 'Recurrence', type: 'select', options: ['One time', 'Weekly'] }),
      field({ key: 'family', label: 'Family booking', type: 'select', options: ['Select enquiry'] }),
      field({ key: 'waitlistEnabled', label: 'Enable waitlist', type: 'boolean' }),
    ],
  }),
  AD6: mutable({
    purpose: 'Balance enquiry assignment across counselors and monitor workload.',
    description: 'Auto-assignment rules with counselor capacity, response-time, and conversion metrics.',
    primaryAction: 'Save Assignment Rules', recordNoun: 'counselor assignment rule', tabs: [], segments: [], statusChoices: ['Active', 'On Leave', 'Inactive'],
    fields: [
      field({ key: 'assignmentMode', label: 'Assignment mode', type: 'select', required: true, options: ['Round-robin', 'By current workload'] }),
      field({ key: 'counselor', label: 'Counselor', type: 'select', required: true, options: ['Select counselor'] }),
      field({ key: 'dailyCap', label: 'Daily enquiry cap', type: 'number', required: true }),
      field({ key: 'acceptsAssignments', label: 'Accept new assignments', type: 'boolean' }),
      field({ key: 'reassignmentTarget', label: 'Reassignment target', type: 'select', options: ['Distribute automatically', 'Select counselor'] }),
    ],
  }),
  AC3: mutable({
    purpose: 'Define the institute grading model, bands, and report-card weightage.',
    description: 'Default percentage, GPA, letter-grade, or custom rubric with per-class overrides.',
    primaryAction: 'Save Grading Scale', recordNoun: 'grading scale', tabs: ['Grading Bands', 'Report Card Weightage'], segments: [], statusChoices: ['Draft', 'Active'],
    fields: [
      field({ key: 'approach', label: 'Grading approach', type: 'select', required: true, options: ['Percentage', 'GPA', 'Letter Grade', 'Custom'] }),
      field({ key: 'bandLabel', label: 'Band label', type: 'text', required: true }),
      field({ key: 'minimumScore', label: 'Minimum score', type: 'number', required: true }),
      field({ key: 'maximumScore', label: 'Maximum score', type: 'number', required: true }),
      field({ key: 'gradePoint', label: 'Grade point', type: 'number' }),
      field({ key: 'rubricDescription', label: 'Rubric description', type: 'textarea' }),
      field({ key: 'assessmentType', label: 'Assessment type', type: 'select', options: ['Unit Test', 'Mid-term', 'Common Test', 'Final Exam'] }),
      field({ key: 'weightPercent', label: 'Weight percentage', type: 'number' }),
      field({ key: 'classOverride', label: 'Class override', type: 'select', options: ['Institute default', 'Select class'] }),
    ],
  }),
  AC4: mutable({
    purpose: 'Create and oversee assessments and exam publication across the active scope.',
    description: 'Assessment register with class, subject, term, marks lifecycle, and common-test visibility.',
    primaryAction: 'New Assessment', recordNoun: 'assessment', tabs: [], segments: [],
    statusChoices: ['Draft', 'Marks Pending', 'Submitted', 'Published'],
    fields: [
      field({ key: 'name', label: 'Assessment name', type: 'text', required: true }),
      field({ key: 'class', label: 'Class', type: 'select', required: true, options: ['Select class'] }),
      field({ key: 'subject', label: 'Subject', type: 'select', required: true, options: ['Select subject'] }),
      field({ key: 'academicYear', label: 'Academic year', type: 'select', required: true, options: ['Current academic year'] }),
      field({ key: 'term', label: 'Term', type: 'select', required: true, options: ['Term 1', 'Term 2', 'Annual'] }),
      field({ key: 'maximumMarks', label: 'Maximum marks', type: 'number', required: true }),
      field({ key: 'assessmentDate', label: 'Assessment date', type: 'date', required: true }),
      field({ key: 'commonTest', label: 'Make this a common test', type: 'boolean', hint: 'Multi-branch tests continue in the Common Test Builder.' }),
    ],
  }),
  AC5: mutable({
    purpose: 'Create a fair, synchronized assessment spanning branches and sections.',
    description: 'Seven-step common-test workflow covering targeting, scheduling, paper, weightage, and fairness.',
    primaryAction: 'Create Common Test', recordNoun: 'common test',
    tabs: ['Basics', 'Targeting', 'Scheduling', 'Question Paper', 'Weightage', 'Fairness Controls', 'Review & Create'], segments: [],
    statusChoices: ['Draft', 'Scheduled', 'Marks Pending', 'Submitted', 'Published'],
    fields: [
      field({ key: 'name', label: 'Test name', type: 'text', required: true }),
      field({ key: 'subject', label: 'Subject', type: 'select', required: true, options: ['Select subject'] }),
      field({ key: 'class', label: 'Class or grade', type: 'select', required: true, options: ['Select class'] }),
      field({ key: 'term', label: 'Term', type: 'select', required: true, options: ['Term 1', 'Term 2', 'Annual'] }),
      field({ key: 'maximumMarks', label: 'Maximum marks', type: 'number', required: true }),
      field({ key: 'branches', label: 'Target branches', type: 'select', required: true, options: ['All branches', 'Specific branches'] }),
      field({ key: 'sections', label: 'Target sections', type: 'select', required: true, options: ['All sections', 'Specific sections'] }),
      field({ key: 'scheduleMode', label: 'Scheduling mode', type: 'select', required: true, options: ['Same date and time', 'Branch date window'] }),
      field({ key: 'startsAt', label: 'Common start', type: 'datetime' }),
      field({ key: 'windowEnd', label: 'Scheduling window ends', type: 'datetime' }),
      field({ key: 'paperMode', label: 'Question paper mode', type: 'select', required: true, options: ['Shared locked paper', 'Shared question bank'] }),
      field({ key: 'randomizeByBranch', label: 'Randomize per branch', type: 'boolean' }),
      field({ key: 'reportCardWeight', label: 'Report-card weight percentage', type: 'number' }),
      field({ key: 'leaderboardFormula', label: 'Leaderboard points formula', type: 'select', options: ['None', 'Percentage × weight', 'Rank-based bonus'] }),
      field({ key: 'normalization', label: 'Normalization', type: 'select', options: ['None', 'Z-score', 'Percentile'] }),
      field({ key: 'simultaneousRelease', label: 'Release results simultaneously', type: 'boolean' }),
    ],
  }),
  AC6: mutable({
    purpose: 'Design, generate, review, and publish report cards.',
    description: 'Branded template configuration and tracked batch generation by class, section, and term.',
    primaryAction: 'Generate Report Cards', recordNoun: 'report card batch', tabs: [],
    segments: ['Template', 'Generate & Track'], statusChoices: ['Pending Remarks', 'Generating', 'Generated', 'Failed', 'Published'],
    fields: [
      field({ key: 'includeMarks', label: 'Include marks table', type: 'boolean' }),
      field({ key: 'includeAttendance', label: 'Include attendance summary', type: 'boolean' }),
      field({ key: 'includeRemarks', label: 'Include teacher remarks', type: 'boolean' }),
      field({ key: 'includeCoScholastic', label: 'Include co-scholastic grades', type: 'boolean' }),
      field({ key: 'includeHolisticProgress', label: 'Include NEP Holistic Progress Card', type: 'boolean' }),
      field({ key: 'signatureBlocks', label: 'Signature blocks', type: 'textarea', hint: 'One role or signatory per line.' }),
      field({ key: 'class', label: 'Class', type: 'select', required: true, options: ['Select class'] }),
      field({ key: 'section', label: 'Section', type: 'select', required: true, options: ['Select section'] }),
      field({ key: 'term', label: 'Term', type: 'select', required: true, options: ['Term 1', 'Term 2', 'Annual'] }),
    ],
  }),
  AC7: readOnly({
    purpose: 'Monitor syllabus completion and identify subjects behind expected pace.',
    description: 'Read-only class and subject progress with branch filters and reminder shortcuts.',
    recordNoun: 'syllabus progress record', tabs: [], segments: [], statusChoices: ['On Track', 'Behind Schedule'],
    fields: [
      field({ key: 'branchFilter', label: 'Branch', type: 'select', options: ['All branches', 'Select branch'] }),
      field({ key: 'classFilter', label: 'Class', type: 'select', options: ['All classes', 'Select class'] }),
      field({ key: 'subjectFilter', label: 'Subject', type: 'select', options: ['All subjects', 'Select subject'] }),
      field({ key: 'expectedPacePercent', label: 'Expected pace threshold', type: 'number', hint: 'Used only to flag progress; syllabus completion is updated by teachers.' }),
    ],
  }),
  AT2: mutable({
    purpose: 'Set attendance-alert policy and review students below the eligibility threshold.',
    description: 'Threshold, recipient, and frequency controls above the current concern list.',
    primaryAction: 'Save Policy', recordNoun: 'attendance alert policy', tabs: [], segments: [], statusChoices: ['Below Threshold', 'Recovered'],
    fields: [
      field({ key: 'thresholdPercent', label: 'Attendance threshold percentage', type: 'number', required: true }),
      field({ key: 'recipients', label: 'Alert recipients', type: 'select', required: true, options: ['Parent', 'Admin', 'Both'] }),
      field({ key: 'frequency', label: 'Alert frequency', type: 'select', required: true, options: ['Immediately on crossing', 'Weekly digest'] }),
      field({ key: 'manualMessage', label: 'Manual reminder message', type: 'textarea' }),
    ],
  }),
  AT3: mutable({
    purpose: 'Track and correct staff attendance independently of student attendance.',
    description: 'Daily and monthly staff attendance with manual or biometric capture context.',
    primaryAction: 'Mark / Correct Staff Attendance', recordNoun: 'staff attendance record', tabs: [], segments: ['Daily', 'Monthly'],
    statusChoices: ['Present', 'Absent', 'Half Day', 'On Leave'],
    fields: [
      field({ key: 'staffMember', label: 'Staff member', type: 'select', required: true, options: ['Select staff member'] }),
      field({ key: 'attendanceDate', label: 'Attendance date', type: 'date', required: true }),
      field({ key: 'status', label: 'Attendance status', type: 'select', required: true, options: ['Present', 'Absent', 'Half Day', 'On Leave'] }),
      field({ key: 'captureMode', label: 'Capture mode', type: 'select', required: true, options: ['Manual', 'Biometric'] }),
      field({ key: 'note', label: 'Correction note', type: 'textarea', hint: 'Explain any correction to an existing attendance record.' }),
    ],
  }),
  FN1: mutable({
    purpose: 'Define fee heads, applicability, installments, and discount rules.',
    description: 'Institute fee structure with per-class amounts and student-assignment controls.',
    primaryAction: 'Add Fee Head', recordNoun: 'fee head', tabs: [], segments: [], statusChoices: ['Active', 'Inactive', 'Unassigned'],
    fields: [
      field({ key: 'name', label: 'Fee head name', type: 'text', required: true }),
      field({ key: 'type', label: 'Fee type', type: 'select', required: true, options: ['One-time', 'Recurring'] }),
      field({ key: 'frequency', label: 'Frequency', type: 'select', required: true, options: ['Once', 'Monthly', 'Quarterly', 'Term-wise', 'Annual'] }),
      field({ key: 'baseAmount', label: 'Base amount', type: 'number', required: true }),
      field({ key: 'applicableClasses', label: 'Applicable classes', type: 'select', required: true, options: ['All classes', 'Specific classes'] }),
      field({ key: 'siblingDiscountPercent', label: 'Sibling discount percentage', type: 'number' }),
      field({ key: 'rteHandling', label: 'Scholarship / RTE handling', type: 'select', options: ['Standard charge', 'Exempt', 'Custom amount'] }),
      field({ key: 'installmentCount', label: 'Number of installments', type: 'number' }),
      field({ key: 'firstDueDate', label: 'First due date', type: 'date' }),
    ],
  }),
  FN3: mutable({
    purpose: 'Focus fee follow-up on students with materially overdue balances.',
    description: 'Days-overdue prioritized list with parent contact, reminder, escalation, and export.',
    primaryAction: 'Send Reminder', recordNoun: 'fee defaulter case', tabs: [], segments: [], statusChoices: ['Reminder Due', 'Reminder Sent', 'Escalated', 'Resolved'],
    fields: [
      field({ key: 'student', label: 'Student', type: 'select', required: true, options: ['Select student'] }),
      field({ key: 'minimumDaysOverdue', label: 'Minimum days overdue', type: 'number' }),
      field({ key: 'minimumAmountOverdue', label: 'Minimum amount overdue', type: 'number' }),
      field({ key: 'channel', label: 'Reminder channel', type: 'select', required: true, options: ['Push', 'WhatsApp', 'Email'] }),
      field({ key: 'message', label: 'Reminder message', type: 'textarea', required: true }),
      field({ key: 'escalationNote', label: 'Escalation note', type: 'textarea' }),
    ],
  }),
  FN4: mutable({
    purpose: 'Calculate, approve, and record refunds associated with withdrawal or transfer.',
    description: 'Refund workflow retaining paid, refundable, method, and decision history.',
    primaryAction: 'Process Refund', recordNoun: 'refund', tabs: [], segments: [],
    statusChoices: ['Pending', 'Processed', 'Rejected'],
    fields: [
      field({ key: 'student', label: 'Student', type: 'select', required: true, options: ['Select withdrawn student'] }),
      field({ key: 'withdrawalDate', label: 'Withdrawal date', type: 'date', required: true }),
      field({ key: 'amountPaid', label: 'Amount paid', type: 'number', required: true }),
      field({ key: 'refundableAmount', label: 'Refundable amount', type: 'number', required: true }),
      field({ key: 'paymentMethod', label: 'Refund method', type: 'select', required: true, options: ['Original payment method', 'Bank transfer', 'Cheque', 'Cash'] }),
      field({ key: 'decision', label: 'Decision', type: 'select', required: true, options: ['Process', 'Reject'] }),
      field({ key: 'reason', label: 'Calculation or rejection note', type: 'textarea', required: true }),
    ],
  }),
  CM1: mutable({
    purpose: 'Publish circulars and urgent broadcasts to permission-appropriate audiences.',
    description: 'Institute, branch, or class-section communication with attachments and read receipts.',
    primaryAction: 'New Circular', recordNoun: 'circular', tabs: [], segments: [], statusChoices: ['Draft', 'Scheduled', 'Published'],
    fields: [
      field({ key: 'title', label: 'Title', type: 'text', required: true }),
      field({ key: 'body', label: 'Message', type: 'textarea', required: true }),
      field({ key: 'attachmentReference', label: 'Attachment reference', type: 'text' }),
      field({ key: 'scope', label: 'Audience scope', type: 'select', required: true, options: ['Institute-wide', 'Specific branch', 'Specific class-sections'], hint: 'Options are restricted to the current admin’s circular permissions.' }),
      field({ key: 'audience', label: 'Branches or class-sections', type: 'select', options: ['Select audience'] }),
      field({ key: 'publishAt', label: 'Publish at', type: 'datetime' }),
      field({ key: 'emergencyBroadcast', label: 'Emergency broadcast', type: 'boolean', hint: 'Overrides normal parent notification preferences after confirmation.' }),
    ],
  }),
  CM2: mutable({
    purpose: 'Create reusable messages for recurring manual and automated notifications.',
    description: 'Trigger-grouped templates with channel-specific copy, merge fields, and live preview.',
    primaryAction: 'New Template', recordNoun: 'message template', tabs: ['Editor', 'Preview'], segments: [], statusChoices: ['Draft', 'Active', 'Inactive'],
    fields: [
      field({ key: 'name', label: 'Template name', type: 'text', required: true }),
      field({ key: 'trigger', label: 'Trigger type', type: 'select', required: true, options: ['Absence', 'Fee Reminder', 'Low Attendance', 'Marks Published', 'Custom'] }),
      field({ key: 'channel', label: 'Channel', type: 'select', required: true, options: ['Push', 'WhatsApp', 'Email'] }),
      field({ key: 'subject', label: 'Subject', type: 'text' }),
      field({ key: 'body', label: 'Template body', type: 'textarea', required: true, hint: 'Supports approved merge fields such as {student_name}, {amount_due}, and {date}.' }),
      field({ key: 'isDefault', label: 'Default for this trigger', type: 'boolean' }),
    ],
  }),
  TT1: mutable({
    purpose: 'Build conflict-free weekly class and teacher timetables.',
    description: 'Per-section day-by-period schedule with live teacher clash detection and separate publication.',
    primaryAction: 'Save Timetable', recordNoun: 'timetable', tabs: [], segments: ['Draft', 'Published'], statusChoices: ['Draft', 'Published'],
    fields: [
      field({ key: 'classSection', label: 'Class-section', type: 'select', required: true, options: ['Select class-section'] }),
      field({ key: 'day', label: 'Day', type: 'select', required: true, options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] }),
      field({ key: 'period', label: 'Period', type: 'number', required: true }),
      field({ key: 'subject', label: 'Subject', type: 'select', required: true, options: ['Select subject'] }),
      field({ key: 'teacher', label: 'Teacher', type: 'select', required: true, options: ['Select available teacher'] }),
      field({ key: 'room', label: 'Room', type: 'text' }),
    ],
  }),
  TT2: mutable({
    purpose: 'Cover timetable periods when the assigned teacher is unavailable.',
    description: 'Date-scoped substitution queue filtered to free and qualified staff.',
    primaryAction: 'Assign Substitute', recordNoun: 'substitution', tabs: [], segments: [],
    statusChoices: ['Unassigned', 'Assigned', 'Notified'],
    fields: [
      field({ key: 'date', label: 'Date', type: 'date', required: true }),
      field({ key: 'classSection', label: 'Class-section', type: 'select', required: true, options: ['Select class-section'] }),
      field({ key: 'period', label: 'Period', type: 'number', required: true }),
      field({ key: 'subject', label: 'Subject', type: 'select', required: true, options: ['Select subject'] }),
      field({ key: 'originalTeacher', label: 'Original teacher', type: 'select', required: true, options: ['Select unavailable teacher'] }),
      field({ key: 'substituteTeacher', label: 'Substitute teacher', type: 'select', required: true, options: ['Select free qualified staff'] }),
      field({ key: 'notifyAffectedParents', label: 'Notify affected parents', type: 'boolean' }),
    ],
  }),
  RG1: mutable({
    purpose: 'Maintain the institute taxonomy for point categories and awardable activities.',
    description: 'Locked platform categories plus configurable activities with anti-gaming frequency limits.',
    primaryAction: 'Add Category', recordNoun: 'point category or activity type', tabs: [],
    segments: ['Categories', 'Activity Types'], statusChoices: ['Active', 'Inactive'],
    fields: [
      field({ key: 'recordType', label: 'Definition type', type: 'select', required: true, options: ['Category', 'Activity Type'] }),
      field({ key: 'name', label: 'Name', type: 'text', required: true }),
      field({ key: 'description', label: 'Description', type: 'textarea' }),
      field({ key: 'category', label: 'Category', type: 'select', options: ['Select category'] }),
      field({ key: 'defaultPoints', label: 'Default points', type: 'number' }),
      field({ key: 'requiresManualAward', label: 'Requires manual award', type: 'boolean' }),
      field({ key: 'frequencyCap', label: 'Maximum award frequency', type: 'select', options: ['Unlimited', 'Once per day', 'Once per week', 'Once per month'] }),
      field({ key: 'active', label: 'Active', type: 'boolean' }),
    ],
  }),
  RG2: mutable({
    purpose: 'Define badge criteria, tiers, validity, points, and visibility.',
    description: 'Platform and institute badge catalog with sensitive-badge safeguards.',
    primaryAction: 'New Batch', recordNoun: 'batch', tabs: ['Definition', 'Visibility'], segments: [], statusChoices: ['Active', 'Inactive'],
    fields: [
      field({ key: 'name', label: 'Batch name', type: 'text', required: true }),
      field({ key: 'category', label: 'Category', type: 'select', required: true, options: ['Academic', 'Sports', 'Arts & Culture', 'Leadership', 'Discipline', 'Attendance', 'Community', 'Special'] }),
      field({ key: 'criteriaType', label: 'Criteria type', type: 'select', required: true, options: ['Points threshold', 'Rank threshold', 'Manual award'] }),
      field({ key: 'criteriaValue', label: 'Criteria value', type: 'number' }),
      field({ key: 'tier', label: 'Tier', type: 'select', options: ['None', 'Bronze', 'Silver', 'Gold'] }),
      field({ key: 'validityDays', label: 'Validity in days', type: 'number' }),
      field({ key: 'bonusPoints', label: 'Bonus points', type: 'number' }),
      field({ key: 'sensitive', label: 'Mark as sensitive', type: 'boolean', hint: 'Sensitive batches never appear in public or classmate-visible rankings.' }),
      field({ key: 'active', label: 'Active', type: 'boolean' }),
    ],
  }),
  RG3: mutable({
    purpose: 'Control leaderboard privacy, visibility, anonymization, and network participation.',
    description: 'Institute-level safeguards for how minors appear to parents, peers, and partner institutes.',
    primaryAction: 'Save Settings', recordNoun: 'leaderboard setting', tabs: [], segments: [], statusChoices: ['Enabled', 'Disabled'],
    fields: [
      field({ key: 'parentVisibility', label: 'Parent visibility', type: 'boolean' }),
      field({ key: 'parentVisibilityMode', label: 'Parent visibility mode', type: 'select', options: ["My child's rank + top 10 only", 'Full class or branch leaderboard'] }),
      field({ key: 'anonymizeBelowGrade', label: 'Anonymize below grade', type: 'number' }),
      field({ key: 'studentOptOut', label: 'Allow student or parent opt-out', type: 'boolean' }),
      field({ key: 'networkRealNames', label: 'Show real names on network leaderboard', type: 'boolean' }),
      field({ key: 'globalParticipation', label: 'Participate in global network leaderboard', type: 'boolean', hint: 'Reducing privacy requires explicit confirmation and is audit logged.' }),
    ],
  }),
  RG4: readOnly({
    purpose: 'Inspect current institute rankings across points, batches, and improvement.',
    description: 'Read-only leaderboard with scope, category, period, and branch filters.',
    recordNoun: 'leaderboard entry', tabs: ['Points Leaderboard', 'Batch Leaderboard', 'Most-Improved Leaderboard'], segments: [], statusChoices: [],
    fields: [
      field({ key: 'scopeFilter', label: 'Scope', type: 'select', options: ['Class', 'Branch', 'Institute', 'Network'] }),
      field({ key: 'categoryFilter', label: 'Category', type: 'select', options: ['All categories', 'Select category'] }),
      field({ key: 'periodFilter', label: 'Time period', type: 'select', options: ['This week', 'This month', 'This term', 'Academic year'] }),
      field({ key: 'branchFilter', label: 'Branch', type: 'select', options: ['All branches', 'Select branch'] }),
    ],
  }),
  RG5: mutable({
    purpose: 'Establish and manage bilateral leaderboard partnerships with other institutes.',
    description: 'Incoming and outgoing partnership requests with explicit participant scope.',
    primaryAction: 'Request Partnership', recordNoun: 'partnership',
    tabs: ['Active', 'Pending', 'Sent', 'Declined & Withdrawn'], segments: [],
    statusChoices: ['Pending', 'Active', 'Declined', 'Withdrawn'],
    fields: [
      field({ key: 'partnerInstitute', label: 'Partner institute', type: 'select', required: true, options: ['Search institute directory'] }),
      field({ key: 'scope', label: 'Partnership scope', type: 'select', required: true, options: ['All students', 'Specific grades', 'Specific subjects'] }),
      field({ key: 'grades', label: 'Included grades', type: 'select', options: ['Select grades'] }),
      field({ key: 'subjects', label: 'Included subjects', type: 'select', options: ['Select subjects'] }),
      field({ key: 'response', label: 'Request response', type: 'select', options: ['Accept', 'Decline'] }),
      field({ key: 'responseNote', label: 'Response note', type: 'textarea' }),
    ],
  }),
  RG6: mutable({
    purpose: 'Review high-value manual point and batch awards submitted for a second approval.',
    description: 'Pending awards require a different approver; approving posts the award to the student ledger, while rejection always records a reason.',
    primaryAction: 'Review Award', recordNoun: 'award approval', tabs: ['Pending', 'Approved', 'Rejected'], segments: [],
    statusChoices: ['Pending', 'Approved', 'Rejected'],
    fields: [
      field({ key: 'student', label: 'Student', type: 'select', required: true, options: ['Select student'] }),
      field({ key: 'category', label: 'Point category', type: 'select', required: true, options: ['Select category'] }),
      field({ key: 'points', label: 'Points', type: 'number', required: true }),
      field({ key: 'note', label: 'Award note', type: 'textarea', required: true }),
      field({ key: 'requestedBy', label: 'Requested by', type: 'select', required: true, options: ['Select requesting staff member'] }),
      field({ key: 'decision', label: 'Decision', type: 'select', required: true, options: ['Approve', 'Reject'] }),
      field({ key: 'approvalNote', label: 'Approval or rejection note', type: 'textarea', hint: 'A rejection reason is required before declining an award.' }),
    ],
  }),
  RA1: readOnly({
    purpose: 'Provide one organized entry point to every pre-built institute report.',
    description: 'Read-only report catalog grouped by module with scoped previews and scheduling links.',
    recordNoun: 'report', tabs: ['Attendance', 'Academics', 'Admissions', 'Fees', 'Leaderboard'], segments: [], statusChoices: [],
    fields: [
      field({ key: 'moduleFilter', label: 'Module', type: 'select', options: ['All modules', 'Attendance', 'Academics', 'Admissions', 'Fees', 'Leaderboard'] }),
      field({ key: 'dateFrom', label: 'From date', type: 'date' }),
      field({ key: 'dateTo', label: 'To date', type: 'date' }),
      field({ key: 'branchFilter', label: 'Branch', type: 'select', options: ['All branches', 'Select branch'] }),
    ],
  }),
  RA2: mutable({
    purpose: 'Compose reusable reports from permitted institute data sources.',
    description: 'Step-based source, field, filter, aggregation, visualization, preview, and scheduling workflow.',
    primaryAction: 'Run Report', recordNoun: 'custom report',
    tabs: ['Data Source', 'Fields', 'Filters', 'Grouping', 'Visualization', 'Preview'], segments: [],
    statusChoices: ['Draft', 'Saved'],
    fields: [
      field({ key: 'name', label: 'Report name', type: 'text', required: true }),
      field({ key: 'dataSource', label: 'Data source', type: 'select', required: true, options: ['Students', 'Attendance', 'Marks', 'Fees', 'Points'] }),
      field({ key: 'columns', label: 'Fields and columns', type: 'select', required: true, options: ['Select fields'] }),
      field({ key: 'filters', label: 'Filters', type: 'textarea', hint: 'Define field, operator, and value for each filter.' }),
      field({ key: 'aggregation', label: 'Aggregation', type: 'select', options: ['None', 'Count', 'Sum', 'Average'] }),
      field({ key: 'groupBy', label: 'Group by', type: 'select', options: ['None', 'Select field'] }),
      field({ key: 'visualization', label: 'Visualization', type: 'select', required: true, options: ['Table', 'Bar', 'Line'] }),
      field({ key: 'schedule', label: 'Email schedule', type: 'select', options: ['None', 'Daily', 'Weekly', 'Monthly'] }),
    ],
  }),
  AO1: mutable({
    purpose: 'Manage routes, fleet, and student transport assignments.',
    description: 'Subscription-gated transport operations with GPS state and parent alert tools.',
    primaryAction: 'Add Route', recordNoun: 'transport record', tabs: [],
    segments: ['Routes', 'Vehicles', 'Student Assignments'], statusChoices: ['Active', 'Inactive', 'GPS Offline'],
    fields: [
      field({ key: 'recordType', label: 'Record type', type: 'select', required: true, options: ['Route', 'Vehicle', 'Student Assignment'] }),
      field({ key: 'routeName', label: 'Route name', type: 'text' }),
      field({ key: 'stops', label: 'Stops', type: 'textarea', hint: 'Enter stops in travel order, one per line.' }),
      field({ key: 'vehicle', label: 'Assigned vehicle', type: 'select', options: ['Unassigned', 'Select vehicle'] }),
      field({ key: 'registrationNumber', label: 'Vehicle registration', type: 'text' }),
      field({ key: 'capacity', label: 'Vehicle capacity', type: 'number' }),
      field({ key: 'driverContact', label: 'Driver contact', type: 'text' }),
      field({ key: 'gpsDeviceId', label: 'GPS device ID', type: 'text' }),
      field({ key: 'student', label: 'Student', type: 'select', options: ['Select student'] }),
      field({ key: 'boardingStop', label: 'Boarding stop', type: 'select', options: ['Select route stop'] }),
    ],
  }),
  AO2: mutable({
    purpose: 'Operate the book catalog, circulation, and overdue-fine ledger.',
    description: 'Catalog maintenance plus scan-friendly issue, return, and fine workflows.',
    primaryAction: 'Add Book', recordNoun: 'library record', tabs: [],
    segments: ['Catalog', 'Issue/Return', 'Fines'], statusChoices: ['Available', 'Issued', 'Overdue', 'Pending', 'Paid', 'Waived'],
    fields: [
      field({ key: 'title', label: 'Book title', type: 'text', required: true }),
      field({ key: 'author', label: 'Author', type: 'text', required: true }),
      field({ key: 'isbn', label: 'ISBN', type: 'text' }),
      field({ key: 'copyCount', label: 'Number of copies', type: 'number', required: true }),
      field({ key: 'bookCopy', label: 'Book or copy barcode', type: 'text' }),
      field({ key: 'student', label: 'Student', type: 'select', options: ['Select student'] }),
      field({ key: 'dueDate', label: 'Due date', type: 'date' }),
      field({ key: 'transaction', label: 'Circulation action', type: 'select', options: ['Issue', 'Return'] }),
      field({ key: 'fineAmount', label: 'Fine amount', type: 'number' }),
      field({ key: 'waiverReason', label: 'Fine waiver reason', type: 'textarea' }),
    ],
  }),
  AO3: mutable({
    purpose: 'Manage hostel beds, visitors, and daily meal participation.',
    description: 'Boarding operations spanning allocation, safety logs, and catering counts.',
    primaryAction: 'Assign Room', recordNoun: 'hostel record', tabs: [],
    segments: ['Room Allocation', 'Visitor Log', 'Meal Tracking'], statusChoices: ['Vacant', 'Occupied', 'Checked In', 'Checked Out', 'Present', 'Absent'],
    fields: [
      field({ key: 'student', label: 'Boarding student', type: 'select', options: ['Select student'] }),
      field({ key: 'room', label: 'Room', type: 'select', options: ['Select room'] }),
      field({ key: 'bed', label: 'Bed', type: 'select', options: ['Select vacant bed'] }),
      field({ key: 'allocationStart', label: 'Allocation start date', type: 'date' }),
      field({ key: 'visitorName', label: 'Visitor name', type: 'text' }),
      field({ key: 'studentVisited', label: 'Student visited', type: 'select', options: ['Select student'] }),
      field({ key: 'checkInAt', label: 'Check-in time', type: 'datetime' }),
      field({ key: 'checkOutAt', label: 'Check-out time', type: 'datetime' }),
      field({ key: 'mealDate', label: 'Meal date', type: 'date' }),
      field({ key: 'meal', label: 'Meal', type: 'select', options: ['Breakfast', 'Lunch', 'Dinner'] }),
      field({ key: 'mealPresent', label: 'Mess attendance', type: 'boolean' }),
    ],
  }),
  SE2: mutable({
    purpose: 'Set institute-wide academic, language, currency, and regional defaults.',
    description: 'Shared defaults with links to detailed grading and leaderboard configuration.',
    primaryAction: 'Save Changes', recordNoun: 'academic and regional setting', tabs: ['Academic', 'Language & Region'], segments: [], statusChoices: ['Active'],
    fields: [
      field({ key: 'academicYearStartMonth', label: 'Academic year start month', type: 'select', required: true, options: ['January', 'April', 'June', 'July', 'September'] }),
      field({ key: 'defaultGradingScale', label: 'Default grading scale', type: 'select', required: true, options: ['Select grading scale'] }),
      field({ key: 'mediumOfInstruction', label: 'Medium of instruction', type: 'select', required: true, options: ['English', 'Hindi', 'Regional language', 'Bilingual'] }),
      field({ key: 'interfaceLanguage', label: 'Default language', type: 'select', required: true, options: ['English', 'Hindi'] }),
      field({ key: 'currency', label: 'Currency', type: 'select', required: true, options: ['INR', 'AED', 'USD'] }),
      field({ key: 'locale', label: 'Date and number format', type: 'select', required: true, options: ['English (India)', 'Hindi (India)', 'English (United States)'] }),
      field({ key: 'leaderboardVisibleByDefault', label: 'Leaderboards visible by default', type: 'boolean' }),
    ],
  }),
  SE3: mutable({
    purpose: 'Review subscription entitlement, usage, invoices, and payment details.',
    description: 'Plan and billing view with limit warnings and platform-mediated upgrades.',
    primaryAction: 'Upgrade Plan', recordNoun: 'subscription', tabs: ['Current Plan', 'Usage', 'Billing History'], segments: [],
    statusChoices: ['Trial', 'Active', 'Past Due', 'Cancelled'],
    fields: [
      field({ key: 'targetPlan', label: 'Requested plan', type: 'select', required: true, options: ['Select available plan'] }),
      field({ key: 'billingCycle', label: 'Billing cycle', type: 'select', required: true, options: ['Monthly', 'Annual'] }),
      field({ key: 'requestedStudentLimit', label: 'Required student capacity', type: 'number' }),
      field({ key: 'requestedBranchLimit', label: 'Required branch capacity', type: 'number' }),
      field({ key: 'billingEmail', label: 'Billing email', type: 'email', required: true }),
      field({ key: 'upgradeNote', label: 'Upgrade request note', type: 'textarea' }),
    ],
  }),
  SE4: mutable({
    purpose: 'Govern consent language, retention, and data-subject requests.',
    description: 'DPDP-aligned versioned consent publishing, compliance gaps, retention, export, and deletion queues.',
    primaryAction: 'Publish New Consent Version', recordNoun: 'consent policy version',
    tabs: ['Consent Text', 'Consent Records', 'Retention Policy', 'Data Requests'], segments: [],
    statusChoices: ['Draft', 'Published', 'Superseded', 'Pending', 'In Progress', 'Completed', 'Rejected'],
    fields: [
      field({ key: 'consentType', label: 'Consent type', type: 'select', required: true, options: ['Data processing', 'Photo usage', 'Leaderboard display'] }),
      field({ key: 'versionLabel', label: 'Version label', type: 'text', required: true }),
      field({ key: 'consentText', label: 'Consent text', type: 'textarea', required: true }),
      field({ key: 'effectiveDate', label: 'Effective date', type: 'date', required: true }),
      field({ key: 'requireReconsent', label: 'Require affected parents to consent again', type: 'boolean' }),
      field({ key: 'withdrawnRetentionMonths', label: 'Withdrawn-student retention months', type: 'number', required: true }),
      field({ key: 'graduatedRetentionMonths', label: 'Graduated-student retention months', type: 'number', required: true }),
      field({ key: 'requestDecisionNote', label: 'Data-request decision note', type: 'textarea' }),
    ],
  }),
  SE5: mutable({
    purpose: 'Activate notification channels and maintain their provider credentials.',
    description: 'Push, WhatsApp, and email provider configuration with connection tests.',
    primaryAction: 'Save Channel Settings', recordNoun: 'notification channel',
    tabs: ['Push', 'WhatsApp', 'Email'], segments: [], statusChoices: ['Active', 'Inactive', 'Credential Error'],
    fields: [
      field({ key: 'channel', label: 'Channel', type: 'select', required: true, options: ['Push', 'WhatsApp', 'Email'] }),
      field({ key: 'active', label: 'Active', type: 'boolean' }),
      field({ key: 'provider', label: 'Provider', type: 'select', options: ['Platform default', 'Gupshup', 'Twilio', 'Meta direct', 'SMTP', 'Custom'] }),
      field({ key: 'apiKey', label: 'API key', type: 'text', hint: 'Stored securely and never returned in full after saving.' }),
      field({ key: 'senderId', label: 'Sender ID or phone number', type: 'text' }),
      field({ key: 'smtpHost', label: 'SMTP host', type: 'text' }),
      field({ key: 'smtpPort', label: 'SMTP port', type: 'number' }),
      field({ key: 'username', label: 'Provider username', type: 'text' }),
      field({ key: 'fromEmail', label: 'From email', type: 'email' }),
    ],
  }),
  AL1: readOnly({
    purpose: 'Preserve an accountable history of sensitive institute actions.',
    description: 'Read-only audit trail with user, action, entity, date, and readable before/after filtering.',
    recordNoun: 'audit event', tabs: [], segments: [], statusChoices: [],
    fields: [
      field({ key: 'userFilter', label: 'User', type: 'select', options: ['All users', 'Select user'] }),
      field({ key: 'actionFilter', label: 'Action type', type: 'select', options: ['All actions', 'Create', 'Update', 'Delete', 'Access change', 'Privacy change'] }),
      field({ key: 'entityTypeFilter', label: 'Entity type', type: 'select', options: ['All entities', 'Student', 'Staff', 'Role', 'Branch', 'Setting'] }),
      field({ key: 'fromDate', label: 'From date', type: 'date' }),
      field({ key: 'toDate', label: 'To date', type: 'date' }),
    ],
  }),
  NT1: readOnly({
    purpose: 'Show the signed-in admin approvals, system alerts, and platform announcements.',
    description: 'Read-only notification feed grouped by day and routed to the relevant operational screen.',
    recordNoun: 'notification', tabs: [],
    segments: ['All', 'Approvals Needed', 'System', 'Platform Announcements'], statusChoices: ['Unread', 'Read', 'Dismissed'],
    fields: [
      field({ key: 'categoryFilter', label: 'Category', type: 'select', options: ['All', 'Approvals Needed', 'System', 'Platform Announcements'] }),
      field({ key: 'readStateFilter', label: 'Read state', type: 'select', options: ['All', 'Unread', 'Read'] }),
      field({ key: 'fromDate', label: 'From date', type: 'date' }),
      field({ key: 'toDate', label: 'To date', type: 'date' }),
    ],
  }),
  PR1: mutable({
    purpose: 'Maintain the signed-in admin profile and account security.',
    description: 'Self-scoped profile, password, two-factor authentication, sessions, and permission summary.',
    primaryAction: 'Save Changes', recordNoun: 'account',
    tabs: ['Profile', 'Security', 'My Role & Permissions'], segments: [], statusChoices: ['Active'],
    fields: [
      field({ key: 'name', label: 'Full name', type: 'text', required: true }),
      field({ key: 'phone', label: 'Phone', type: 'text', required: true }),
      field({ key: 'email', label: 'Email', type: 'email', required: true }),
      field({ key: 'photoReference', label: 'Profile photo reference', type: 'text' }),
      field({ key: 'currentPassword', label: 'Current password', type: 'text' }),
      field({ key: 'newPassword', label: 'New password', type: 'text' }),
      field({ key: 'twoFactorEnabled', label: 'Enable two-factor authentication', type: 'boolean' }),
    ],
  }),
  HP1: mutable({
    purpose: 'Find documentation and contact platform support.',
    description: 'Searchable help content, release notes, and a support-request form.',
    primaryAction: 'Submit a Support Request', recordNoun: 'support request',
    tabs: ['Knowledge Base', 'Contact Support', "What's New"], segments: [],
    statusChoices: ['Open', 'In Progress', 'Resolved', 'Closed'],
    fields: [
      field({ key: 'subject', label: 'Subject', type: 'text', required: true }),
      field({ key: 'category', label: 'Category', type: 'select', required: true, options: ['Account access', 'Admissions', 'Academics', 'Attendance', 'Fees', 'Communication', 'Technical issue', 'Other'] }),
      field({ key: 'description', label: 'Description', type: 'textarea', required: true }),
      field({ key: 'screenshotReference', label: 'Screenshot reference', type: 'text' }),
      field({ key: 'contactEmail', label: 'Reply-to email', type: 'email', required: true }),
    ],
  }),
} satisfies { readonly [Id in GenericScreenId]: Omit<ScreenWorkflow, 'id'> }

export function getScreenWorkflow(id: GenericScreenId): ScreenWorkflow {
  return { id, ...screenWorkflows[id] } as ScreenWorkflow
}
