# Generated by Django 5.2.16 on 2026-07-20 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        (
            "institutes",
            "0005_institute_address_line_1_institute_address_line_2_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_code_override", models.CharField(blank=True, max_length=20)),
                ("is_elective", models.BooleanField(default=False)),
                (
                    "periods_per_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "default_max_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_subjects",
                        to="academics.grade",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="institutes.institute",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_curricula",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "class_subjects",
                "ordering": ("sort_order", "subject__name"),
                "indexes": [
                    models.Index(
                        fields=["institute", "grade"],
                        name="class_subje_institu_8144f8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grade", "subject"), name="uq_class_subject"
                    )
                ],
            },
        ),
    ]
