# Generated by Django 5.2.16 on 2026-07-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_classsubject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="class_curricula",
                to="academics.subject",
            ),
        ),
        migrations.AlterField(
            model_name="subjectteacherassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="section_teacher_assignments",
                to="academics.subject",
            ),
        ),
    ]
