# Generated by Django 5.2.16 on 2026-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_classsubject_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classsection",
            name="max_strength",
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
