# Generated by Django 5.1.6 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("academics", "0005_room")]

    operations = [
        migrations.AddField(model_name="room", name="equipment", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name="room", name="floor", field=models.PositiveSmallIntegerField(default=1)),
    ]
