# Generated by Django 5.2 for CampusOne academic operations.
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0006_room_floor_equipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicOperation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("LESSON_PLAN", "Lesson plan"), ("HOMEWORK", "Homework"), ("EXAM", "Exam"), ("QUESTION", "Question"), ("MARK", "Mark")], max_length=24)),
                ("title", models.CharField(max_length=250)),
                ("status", models.CharField(default="DRAFT", max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="academic_operations", to="institutes.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_academic_operations", to=settings.AUTH_USER_MODEL)),
                ("institute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="academic_operations", to="institutes.institute")),
            ],
            options={
                "db_table": "academic_operations",
                "ordering": ("-updated_at", "title"),
                "indexes": [models.Index(fields=["institute", "kind", "-updated_at"], name="academic_op_institu_63d585_idx"), models.Index(fields=["branch", "kind", "status"], name="academic_op_branch__626d7c_idx")],
            },
        ),
    ]
