# Generated by Django 5.2.16 on 2026-08-04 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_academicoperation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "academic_terms",
                "ordering": ("sort_order", "start_date", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("academic_year", "name"),
                        name="uq_academic_term_name_per_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="ck_academic_term_date_order",
                    ),
                ],
            },
        ),
    ]
