# Generated by Django 5.2.16 on 2026-08-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_academicterm"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubject",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_subjects",
                to="academics.room",
            ),
        ),
    ]
