# Generated by Django 5.2.16 on 2026-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_classsubject_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubject",
            name="is_lab",
            field=models.BooleanField(default=False),
        ),
    ]
