# Generated by Django 5.2.16 on 2026-08-13 11:36

from django.conf import settings
from django.db import migrations, models


def copy_sections_forward(apps, schema_editor):
    Assignment = apps.get_model("academics", "SubjectTeacherAssignment")
    Through = Assignment.class_sections.through
    rows = [
        Through(subjectteacherassignment_id=a_id, classsection_id=s_id)
        for a_id, s_id in Assignment.objects.values_list("id", "class_section_id")
        if s_id is not None
    ]
    Through.objects.bulk_create(rows, batch_size=500)


def copy_sections_backward(apps, schema_editor):
    # Lossy for multi-section assignments (only one section is kept, the
    # alphabetically first by section_name) and for zero-section rows (FK
    # left NULL, which the restored NOT NULL constraint will reject).
    Assignment = apps.get_model("academics", "SubjectTeacherAssignment")
    for assignment in Assignment.objects.prefetch_related("class_sections"):
        sections = list(assignment.class_sections.all())
        sections.sort(key=lambda s: s.section_name)
        assignment.class_section_id = sections[0].id if sections else None
        assignment.save(update_fields=["class_section"])


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_classsubject_is_lab"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectteacherassignment",
            name="class_sections",
            field=models.ManyToManyField(
                blank=True,
                related_name="subject_teacher_assignments",
                to="academics.classsection",
            ),
        ),
        migrations.AddField(
            model_name="subjectteacherassignment",
            name="combined_slot_label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        # Made nullable before removal so the reverse migration re-creates the
        # column as nullable before copy_sections_backward repopulates it.
        migrations.AlterField(
            model_name="subjectteacherassignment",
            name="class_section",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=models.deletion.CASCADE,
                related_name="legacy_subject_teacher_assignments",
                to="academics.classsection",
            ),
        ),
        migrations.RunPython(copy_sections_forward, copy_sections_backward),
        migrations.RemoveConstraint(
            model_name="subjectteacherassignment",
            name="uq_section_subject_teacher",
        ),
        migrations.RemoveIndex(
            model_name="subjectteacherassignment",
            name="subject_tea_class_s_a49ff8_idx",
        ),
        migrations.RemoveIndex(
            model_name="subjectteacherassignment",
            name="subject_tea_teacher_605058_idx",
        ),
        migrations.RemoveField(
            model_name="subjectteacherassignment",
            name="class_section",
        ),
        migrations.AddIndex(
            model_name="subjectteacherassignment",
            index=models.Index(
                fields=["teacher"], name="subject_tea_teacher_a0c25e_idx"
            ),
        ),
    ]
