# Generated by Django 5.2.16 on 2026-07-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeinvoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_invoices",
                to="people.student",
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="finance.feeinvoice",
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["institute", "branch", "due_date"],
                name="finance_fee_institu_668605_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["paid_at"], name="finance_fee_paid_at_554a1b_idx"
            ),
        ),
    ]
