# Generated by Django 5.2.16 on 2026-08-12 08:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_financerecord"),
        ("institutes", "0010_avoid_main_branch_code"),
        ("people", "0016_assign_admin_employee_codes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeePlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "academic_year",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("applies_to", models.JSONField(blank=True, default=list)),
                ("items", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FinanceSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_prefix", models.CharField(default="INV", max_length=10)),
                ("receipt_prefix", models.CharField(default="RCP", max_length=10)),
                ("invoice_sequence", models.PositiveIntegerField(default=0)),
                ("receipt_sequence", models.PositiveIntegerField(default=0)),
                (
                    "tax_label",
                    models.CharField(blank=True, default="Tax", max_length=40),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("invoice_footer", models.TextField(blank=True, default="")),
                ("receipt_footer", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("INVOICE", "Invoice"), ("RECEIPT", "Receipt")],
                        default="INVOICE",
                        max_length=10,
                    ),
                ),
                ("layout", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="invoice_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="line_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ISSUED", "Issued"),
                    ("PARTIALLY_PAID", "Partially paid"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ISSUED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="institute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_payments",
                to="institutes.institute",
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("CARD", "Card"),
                    ("BANK", "Bank transfer"),
                    ("CHEQUE", "Cheque"),
                    ("OTHER", "Other"),
                ],
                default="CASH",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="receipt_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["institute", "paid_at"], name="finance_fee_institu_eba53e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feepayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("receipt_number", ""), _negated=True),
                fields=("institute", "receipt_number"),
                name="uq_receipt_number_per_institute",
            ),
        ),
        migrations.AddField(
            model_name="feeplan",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_plans",
                to="institutes.branch",
            ),
        ),
        migrations.AddField(
            model_name="feeplan",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_plans",
                to="institutes.institute",
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="finance.feeplan",
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="institute",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_settings",
                to="institutes.institute",
            ),
        ),
        migrations.AddField(
            model_name="invoicetemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoicetemplate",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_templates",
                to="institutes.institute",
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="finance.invoicetemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["institute", "status"], name="finance_fee_institu_578e9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["institute", "student"], name="finance_fee_institu_8367a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["institute", "due_date"], name="finance_fee_institu_3efc8d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feeinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_number", ""), _negated=True),
                fields=("institute", "invoice_number"),
                name="uq_invoice_number_per_institute",
            ),
        ),
        migrations.AddIndex(
            model_name="feeplan",
            index=models.Index(
                fields=["institute", "is_active"], name="finance_fee_institu_9d38b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicetemplate",
            index=models.Index(
                fields=["institute", "kind"], name="finance_inv_institu_07e7c8_idx"
            ),
        ),
    ]
