# Generated by Django 5.2.16 on 2026-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_backfill_finance_documents"),
        ("institutes", "0010_avoid_main_branch_code"),
        ("people", "0014_remove_inactive_student_guardian_links"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="feeinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("plan__isnull", False),
                    models.Q(("status", "CANCELLED"), _negated=True),
                ),
                fields=("institute", "plan", "student"),
                name="uq_plan_invoice_per_student",
            ),
        ),
    ]
