# Generated by Django 5.2.16 on 2026-08-12 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_plan_invoice_unique"),
        ("institutes", "0010_avoid_main_branch_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoicetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("institute", "kind"),
                name="uq_default_template_per_kind",
            ),
        ),
    ]
