# Generated by Django 5.2.16 on 2026-08-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("finance", "0007_default_template_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feeinvoice",
            name="template",
        ),
        migrations.DeleteModel(
            name="InvoiceTemplate",
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_invoices",
                to="documents.documenttemplate",
            ),
        ),
    ]
