# Generated by Django 5.2.16 on 2026-07-18 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="institutemembership",
            name="uq_membership_scope_role",
        ),
        migrations.AddConstraint(
            model_name="institutemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", True)),
                fields=("user", "institute", "role"),
                name="uq_institute_membership_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="institutemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", False)),
                fields=("user", "institute", "branch", "role"),
                name="uq_branch_membership_role",
            ),
        ),
    ]
