# Generated by Django 5.2.16 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0002_remove_institutemembership_uq_membership_scope_role_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="branch",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_admin_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="branch", name="city", field=models.CharField(blank=True, max_length=100)
        ),
        migrations.AddField(
            model_name="branch", name="email", field=models.EmailField(blank=True, max_length=254)
        ),
        migrations.AddField(
            model_name="branch", name="phone", field=models.CharField(blank=True, max_length=32)
        ),
        migrations.AddField(
            model_name="branch",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="branch", name="state", field=models.CharField(blank=True, max_length=100)
        ),
    ]
