# Generated by Codex for institute onboarding.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [("institutes", "0003_branch_contact_details")]
    operations = [
        migrations.AddField(model_name="branch", name="country", field=models.CharField(default="India", max_length=100)),
        migrations.AddField(model_name="institute", name="display_name", field=models.CharField(blank=True, max_length=200)),
        migrations.AddField(model_name="institute", name="institute_type", field=models.CharField(default="School", max_length=40)),
        migrations.AddField(model_name="institute", name="onboarding_status", field=models.CharField(choices=[("draft", "Draft"), ("pending_review", "Pending review"), ("approved", "Approved"), ("declined", "Declined")], default="draft", max_length=20)),
        migrations.AddField(model_name="institute", name="primary_email", field=models.EmailField(blank=True, max_length=254)),
        migrations.AddField(model_name="institute", name="primary_phone", field=models.CharField(blank=True, max_length=32)),
        migrations.AddField(model_name="institute", name="contact_name", field=models.CharField(blank=True, max_length=200)),
        migrations.AddField(model_name="institute", name="contact_phone", field=models.CharField(blank=True, max_length=32)),
        migrations.AddField(model_name="institute", name="rejection_reason", field=models.TextField(blank=True)),
        migrations.CreateModel(name="SubscriptionPlan", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=100, unique=True)), ("price_per_student", models.DecimalField(decimal_places=2, default=0, max_digits=10)), ("flat_fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)), ("max_branches", models.PositiveIntegerField(default=1)), ("max_students", models.PositiveIntegerField(default=100)), ("features_json", models.JSONField(default=list)), ("is_active", models.BooleanField(default=True))]),
        migrations.CreateModel(name="InstituteDocument", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("document_type", models.CharField(choices=[("affiliation_certificate", "Affiliation Certificate"), ("registration_certificate", "Registration Certificate"), ("pan_card", "PAN Card"), ("gst_certificate", "GST Certificate"), ("other", "Other")], max_length=40)), ("file_name", models.CharField(max_length=255)), ("verified", models.BooleanField(default=False)), ("institute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="institutes.institute"))]),
        migrations.CreateModel(name="InstituteSubscription", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("status", models.CharField(choices=[("trial", "Trial"), ("active", "Active")], default="trial", max_length=20)), ("trial_ends_at", models.DateTimeField()), ("institute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="institutes.institute")), ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="institutes.subscriptionplan"))]),
        migrations.CreateModel(name="InstituteConsentRecord", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("authorized_to_register", models.BooleanField()), ("terms_accepted", models.BooleanField()), ("ip_address", models.GenericIPAddressField(blank=True, null=True)), ("accepted_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), ("institute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="onboarding_consents", to="institutes.institute"))]),
    ]
