# Generated by Django 5.2.16 on 2026-07-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0004_onboarding_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="institute",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="institute",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="institute",
            name="board_affiliation",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="institute",
            name="board_affiliation_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institute",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institute",
            name="contact_designation",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="institute",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="institute",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="institute",
            name="establishment_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="gst_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="institute",
            name="medium_of_instruction",
            field=models.CharField(default="English", max_length=100),
        ),
        migrations.AddField(
            model_name="institute",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="institute",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="institute",
            name="registered_entity_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="institute",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institute",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institute",
            name="udise_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="institute",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("INSTITUTE_ADMIN", "Institute Admin"),
                    ("BRANCH_ADMIN", "Branch Admin"),
                    ("TEACHER", "Teacher"),
                    ("STAFF", "Staff"),
                    ("PARENT", "Parent"),
                ],
                max_length=32,
            ),
        ),
    ]
