# Generated by Django 5.2.16 on 2026-07-24 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "institutes",
            "0005_institute_address_line_1_institute_address_line_2_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituteAssociation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "institute_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_associations_as_one",
                        to="institutes.institute",
                    ),
                ),
                (
                    "institute_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_associations_as_two",
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institute_one", "institute_two"),
                        name="uq_institute_peer_association",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("institute_one", models.F("institute_two")), _negated=True
                        ),
                        name="ck_institute_peer_association_distinct",
                    ),
                ],
            },
        ),
    ]
