# Generated by Django 5.2.16 on 2026-08-20 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_repair_missing_file_support_tables'),
        ('institutes', '0013_repair_missing_institute_association'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRetentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('retention_until', models.DateTimeField()),
                ('delete_reason', models.CharField(max_length=32)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('disposal_started_at', models.DateTimeField(blank=True, null=True)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('public_purge_state', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='NOT_REQUIRED', max_length=16)),
                ('private_delete_state', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('public_delete_state', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='NOT_REQUIRED', max_length=16)),
                ('metadata_state', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageReconciliationIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RETRYING', 'Retrying'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='OPEN', max_length=16)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('safe_details', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_access_logs', to='institutes.branch'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='file_asset_snapshot_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_access_logs', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='outcome',
            field=models.CharField(default='SUCCEEDED', max_length=16),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='purpose',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='reason_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='trace_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_assets', to='institutes.branch'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='checksum_algorithm',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='checksum_value',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='privacy_transition_state',
            field=models.CharField(default='STABLE', max_length=24),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='public_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='public_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='replaces_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_files', to='file_storage.fileasset'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='storage_provider',
            field=models.CharField(default='AZURE', max_length=16),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_upload_sessions', to='institutes.branch'),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='checksum_algorithm',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='content_md5',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='expected_media_type',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='failure_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='required_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='staging_bucket',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='staging_delete_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='staging_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='filevariant',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filevariant',
            name='checksum_algorithm',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='filevariant',
            name='checksum_value',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='filevariant',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filevariant',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='filevariant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='filevariant',
            name='storage_etag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filevariant',
            name='storage_provider',
            field=models.CharField(default='R2', max_length=16),
        ),
        migrations.AlterField(
            model_name='fileaccesslog',
            name='file_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='file_storage.fileasset'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='asset_type',
            field=models.CharField(choices=[('PROFILE_PHOTO', 'Profile photo'), ('LOGO', 'Institute logo'), ('LETTERHEAD', 'Institute letterhead'), ('BANNER', 'Institute banner'), ('GALLERY_IMAGE', 'Gallery image'), ('ID_DOCUMENT', 'Identity document'), ('CERTIFICATE', 'Certificate'), ('MARKSHEET', 'Marksheet'), ('ACADEMIC_NOTE', 'Academic note'), ('OTHER_DOCUMENT', 'Other document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='owner_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('TEACHER', 'Teacher'), ('INSTITUTE', 'Institute'), ('CLASS', 'Class'), ('SUBJECT', 'Subject'), ('TERM', 'Term')], max_length=16),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('QUARANTINED', 'Quarantined'), ('FAILED', 'Failed'), ('DELETED', 'Deleted'), ('AWAITING_UPLOAD', 'Awaiting upload'), ('VERIFYING', 'Verifying'), ('EXPIRED', 'Expired'), ('SOFT_DELETED', 'Soft deleted'), ('DISPOSAL_PENDING', 'Disposal pending'), ('DISPOSAL_FAILED', 'Disposal failed'), ('DISPOSED', 'Disposed')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='fileuploadsession',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPLOADED', 'Uploaded'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=16),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['institute', 'created_at', 'id'], name='file_storag_institu_b2a617_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['file_asset_snapshot_id', 'created_at'], name='file_storag_file_as_d08626_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['institute', 'action', 'outcome', 'created_at'], name='file_storag_institu_637e21_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['institute', 'branch', 'status', 'created_at', 'id'], name='file_storag_institu_fc3baa_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['status', 'updated_at'], name='file_storag_status_65f1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadsession',
            index=models.Index(fields=['status', 'expires_at'], name='file_storag_status_959313_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadsession',
            index=models.Index(fields=['status', 'staging_delete_after'], name='file_storag_status_13d0da_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_file_asset_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='fileuploadsession',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('institute', 'uploaded_by', 'idempotency_key'), name='uq_file_upload_idempotency'),
        ),
        migrations.AddField(
            model_name='fileretentionrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_file_retention_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileretentionrecord',
            name='file_asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_record', to='file_storage.fileasset'),
        ),
        migrations.AddField(
            model_name='fileretentionrecord',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_file_retention_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagereconciliationissue',
            name='file_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_issues', to='file_storage.fileasset'),
        ),
        migrations.AddField(
            model_name='storagereconciliationissue',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_storage_issues', to='institutes.institute'),
        ),
        migrations.AddIndex(
            model_name='storagereconciliationissue',
            index=models.Index(fields=['status', 'issue_type', 'last_seen_at'], name='file_storag_status_e062fb_idx'),
        ),
        migrations.AddIndex(
            model_name='storagereconciliationissue',
            index=models.Index(fields=['institute', 'status', 'last_seen_at'], name='file_storag_institu_fabd0c_idx'),
        ),
    ]
