# Generated by Django 5.2.16 on 2026-08-06 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0010_avoid_main_branch_code"),
        ("platform_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="target_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="target_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="platform_co_target__1a6883_idx",
            ),
        ),
    ]
