# Generated by Django 5.2.16 on 2026-07-21 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_classsection_max_strength"),
        ("attendance", "0002_initial"),
        (
            "institutes",
            "0005_institute_address_line_1_institute_address_line_2_and_more",
        ),
        ("people", "0009_student_aadhar_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="capture_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("qr", "QR"),
                    ("rfid", "RFID"),
                    ("biometric", "Biometric"),
                    ("face", "Face recognition"),
                ],
                default="manual",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="period_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="remark",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "low_attendance_threshold",
                    models.DecimalField(decimal_places=1, default=75, max_digits=4),
                ),
                ("enable_parent_notifications", models.BooleanField(default=True)),
                ("enable_auto_alerts", models.BooleanField(default=True)),
                (
                    "consecutive_absent_threshold",
                    models.PositiveIntegerField(default=3),
                ),
                ("notify_class_teacher", models.BooleanField(default=True)),
                ("notify_branch_admin", models.BooleanField(default=False)),
                ("unmarked_reminder_time", models.TimeField(blank=True, null=True)),
                (
                    "institute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_settings",
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=250)),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("staff", "Staff"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("max_days_per_year", models.PositiveIntegerField(default=0)),
                ("requires_document", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="institutes.institute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "used_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "pending_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="people.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="attendance.leavetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "applicant_type",
                    models.CharField(
                        choices=[("student", "Student"), ("staff", "Staff")],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_days",
                    models.DecimalField(decimal_places=1, default=1, max_digits=5),
                ),
                (
                    "half_day_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("first_half", "First half"),
                            ("second_half", "Second half"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=500)),
                ("rejection_reason", models.CharField(blank=True, max_length=500)),
                (
                    "supporting_document_url",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_leave_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_applications",
                        to="institutes.branch",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="institutes.institute",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="people.student",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="attendance.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ("status", "start_date", "-created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.UniqueConstraint(
                fields=("institute", "name", "applicable_to"),
                name="uq_leave_type_scope",
            ),
        ),
    ]
