# Generated by Django 5.2.16 on 2026-07-21 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_studentattendance_capture_mode_and_more"),
        (
            "institutes",
            "0005_institute_address_line_1_institute_address_line_2_and_more",
        ),
        ("people", "0009_student_aadhar_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(default="marked", max_length=30)),
                ("previous_status", models.CharField(blank=True, max_length=16)),
                ("next_status", models.CharField(blank=True, max_length=16)),
                ("note", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("absence", "Absence"),
                            ("leave_decision", "Leave decision"),
                            ("low_attendance", "Low attendance"),
                            ("unmarked_reminder", "Unmarked reminder"),
                        ],
                        max_length=30,
                    ),
                ),
                ("channel", models.CharField(default="in_app", max_length=20)),
                ("payload", models.JSONField(default=dict)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("disputed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveApplicationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="studentattendance",
            name="uq_student_attendance_per_day",
        ),
        migrations.AddField(
            model_name="attendancesettings",
            name="enabled_capture_modes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="attendancesettings",
            name="parent_acknowledgement_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendancesettings",
            name="staff_leave_routing",
            field=models.CharField(default="branch_admin", max_length=20),
        ),
        migrations.AddField(
            model_name="attendancesettings",
            name="student_leave_routing",
            field=models.CharField(default="class_teacher", max_length=20),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="period_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="subject_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="studentattendance",
            constraint=models.UniqueConstraint(
                fields=("student", "date", "period_id"),
                name="uq_student_attendance_per_period",
            ),
        ),
        migrations.AddField(
            model_name="attendanceauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendanceauditlog",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="attendance.studentattendance",
            ),
        ),
        migrations.AddField(
            model_name="attendanceauditlog",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_audit_events",
                to="institutes.institute",
            ),
        ),
        migrations.AddField(
            model_name="attendancenotification",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_notifications",
                to="institutes.institute",
            ),
        ),
        migrations.AddField(
            model_name="attendancenotification",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.student",
            ),
        ),
        migrations.AddField(
            model_name="attendancenotification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaveapplicationhistory",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaveapplicationhistory",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="attendance.leaveapplication",
            ),
        ),
    ]
