# Generated by Django 5.2.16 on 2026-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_staffattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesettings",
            name="period_wise_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
