# Generated by Django 5.2.16 on 2026-08-14 14:25

from django.db import migrations


def remove_capture_mode_config_if_present(apps, schema_editor):
    model = apps.get_model("attendance", "AttendanceSettings")
    table_name = model._meta.db_table
    existing = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), table_name
        )
    }
    field = model._meta.get_field("capture_mode_config")
    if field.column in existing:
        schema_editor.remove_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendancesettings_capture_mode_config"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_capture_mode_config_if_present,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="attendancesettings",
                    name="capture_mode_config",
                ),
            ],
        ),
    ]
