# Generated by Django 5.2.16 on 2026-07-18 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "institutes",
            "0002_remove_institutemembership_uq_membership_scope_role_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("admission_number", models.CharField(max_length=64)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="institutes.branch",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "ordering": ("first_name", "last_name", "admission_number"),
                "indexes": [
                    models.Index(
                        fields=["institute", "branch", "is_active"],
                        name="people_stud_institu_51d408_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institute", "admission_number"),
                        name="uq_student_admission_number_per_institute",
                    )
                ],
            },
        ),
    ]
