# Generated by Django 5.2.16 on 2026-07-18 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "institutes",
            "0002_remove_institutemembership_uq_membership_scope_role_and_more",
        ),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_code", models.CharField(blank=True, max_length=64)),
                ("invite_pending", models.BooleanField(default=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to="institutes.institute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user__first_name", "user__last_name", "user__email"),
                "indexes": [
                    models.Index(
                        fields=["institute", "invite_pending"],
                        name="people_staf_institu_fc875e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institute", "user"),
                        name="uq_staff_profile_per_institute",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("employee_code", ""), _negated=True),
                        fields=("institute", "employee_code"),
                        name="uq_staff_employee_code_per_institute",
                    ),
                ],
            },
        ),
    ]
