# Generated by Django 5.2 on 2026-07-19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("people", "0003_parentprofile_studentguardian_and_more")]

    operations = [
        migrations.CreateModel(
            name="StaffInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("delivery_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_invitations",
                        to="people.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["staff_profile", "created_at"],
                        name="people_inv_staff_created_idx",
                    ),
                    models.Index(fields=["expires_at"], name="people_inv_expires_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_attempts__gte", 1)),
                        name="ck_staff_invitation_max_attempts",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("consumed_at__isnull", True),
                            ("invalidated_at__isnull", True),
                        ),
                        fields=("staff_profile",),
                        name="uq_active_staff_invitation",
                    ),
                ],
            },
        )
    ]
