# Generated by Django 5.2.16 on 2026-07-19 13:49

import modules.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_staffinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="available_days",
            field=models.JSONField(
                default=modules.people.models.default_teacher_available_days
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="employment_type",
            field=models.CharField(
                choices=[("FULL_TIME", "Full-time"), ("PART_TIME", "Part-time")],
                default="FULL_TIME",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="max_periods_per_day",
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="max_periods_per_week",
            field=models.PositiveSmallIntegerField(default=36),
        ),
    ]
