# Generated by Django 5.2.16 on 2026-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_add_period_four_to_staff_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="attended_special_training",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="belongs_to_bpl",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="belongs_to_disadvantaged_group",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="cwsn_facilities",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_admission",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="deworming_tablets",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="disability_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="free_escort",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="free_hostel_facility",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="free_text_books",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="free_transport",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="getting_free_education",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="habitation_locality",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="iron_folic_acid_tablets",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_examination_appeared",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_examination_passed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_examination_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mdm_beneficiary",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="medium_of_instruction",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="student",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_tongue",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_class",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_year_attendance_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_year_status",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="religion",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="student",
            name="rural_urban",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="student",
            name="social_category",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="student",
            name="sr_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="student",
            name="stream",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="student_nic_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="student",
            name="trade_sector",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="uniform_sets",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="vitamin_a_supplement",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
