# Generated by Django 5.2.16 on 2026-08-13 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutes", "0010_avoid_main_branch_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FEE_INVOICE", "Fee invoice"),
                            ("FEE_RECEIPT", "Fee receipt"),
                            ("MARKSHEET", "Mark sheet"),
                            ("ID_CARD", "ID card"),
                            ("CERTIFICATE", "Certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("layout", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_templates",
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["institute", "category"],
                        name="documents_d_institu_e2b9af_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("institute", "category"),
                        name="uq_default_document_template_per_category",
                    )
                ],
            },
        ),
    ]
