# Generated by Django 5.2.16 on 2026-07-18 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "institutes",
            "0002_remove_institutemembership_uq_membership_scope_role_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("guardian_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENQUIRY", "Enquiry"),
                            ("VISIT_SCHEDULED", "Visit scheduled"),
                            ("APPLIED", "Applied"),
                            ("ENROLLED", "Enrolled"),
                            ("LOST", "Lost"),
                        ],
                        default="ENQUIRY",
                        max_length=32,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enquiries",
                        to="institutes.branch",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["institute", "branch", "status", "created_at"],
                        name="admissions__institu_d71e5d_idx",
                    )
                ],
            },
        ),
    ]
