from datetime import timedelta
from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parents[2]
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

SECRET_KEY = env("DJANGO_SECRET_KEY", default="local-development-only")
DEBUG = env.bool("DJANGO_DEBUG", default=False)
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
THIRD_PARTY_APPS = [
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
]
LOCAL_APPS = [
    "platform_core.apps.PlatformCoreConfig",
    "modules.identity.apps.IdentityConfig",
    "modules.institutes.apps.InstitutesConfig",
    "modules.people.apps.PeopleConfig",
    "modules.admissions.apps.AdmissionsConfig",
    "modules.attendance.apps.AttendanceConfig",
    "modules.finance.apps.FinanceConfig",
    "modules.school_calendar.apps.SchoolCalendarConfig",
    "modules.access_control.apps.AccessControlConfig",
    "modules.admin_console.apps.AdminConsoleConfig",
    "modules.academics.apps.AcademicsConfig",
    "modules.file_storage.apps.FileStorageConfig",
]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "platform_core.middleware.TraceIdMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "config.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]
WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

USE_SQLITE = env.bool("DJANGO_USE_SQLITE", default=False)
if USE_SQLITE:
    DATABASES = {
        "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}
    }
else:
    DATABASES = {"default": env.db("DATABASE_URL")}
    # Persistent connections are useful in production, but they easily exhaust
    # small hosted Postgres plans during local Django development/reloads.
    default_conn_max_age = 0 if DEBUG else 60
    DATABASES["default"]["CONN_MAX_AGE"] = env.int("DATABASE_CONN_MAX_AGE", default=default_conn_max_age)
    if env.bool("DATABASE_SSL_REQUIRE", default=True):
        DATABASES["default"].setdefault("OPTIONS", {})["sslmode"] = "require"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]
LANGUAGE_CODE = "en-in"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Azure Blob Storage is enabled only when explicitly configured. Local and test
# environments remain filesystem-free for metadata tests, while production uses
# private containers and short-lived SAS URLs generated by the API.
AZURE_STORAGE_ACCOUNT_NAME = env("AZURE_STORAGE_ACCOUNT_NAME", default="")
AZURE_STORAGE_ACCOUNT_KEY = env("AZURE_STORAGE_ACCOUNT_KEY", default="")
AZURE_STORAGE_CONNECTION_STRING = env("AZURE_STORAGE_CONNECTION_STRING", default="")
AZURE_STORAGE_ENDPOINT_SUFFIX = env("AZURE_STORAGE_ENDPOINT_SUFFIX", default="core.windows.net")
AZURE_STORAGE_PROFILE_CONTAINER = env("AZURE_STORAGE_PROFILE_CONTAINER", default="profile-images")
AZURE_STORAGE_DOCUMENT_CONTAINER = env("AZURE_STORAGE_DOCUMENT_CONTAINER", default="documents")
AZURE_STORAGE_INSTITUTE_CONTAINER = env(
    "AZURE_STORAGE_INSTITUTE_CONTAINER", default="institute-assets"
)
AZURE_STORAGE_TEMP_CONTAINER = env("AZURE_STORAGE_TEMP_CONTAINER", default="temporary-uploads")
AZURE_STORAGE_SAS_MINUTES = env.int("AZURE_STORAGE_SAS_MINUTES", default=10)
AZURE_STORAGE_REQUIRE_SCAN = env.bool("AZURE_STORAGE_REQUIRE_SCAN", default=False)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "identity.User"

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=["http://localhost:5173"])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=["http://localhost:5173"])

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "platform_core.api.exceptions.api_exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        "identity-login": env("IDENTITY_LOGIN_RATE", default="10/minute"),
        "identity-refresh": env("IDENTITY_REFRESH_RATE", default="30/minute"),
        "institute-onboarding": env("INSTITUTE_ONBOARDING_RATE", default="5/hour"),
    },
}
SPECTACULAR_SETTINGS = {
    "TITLE": "CampusOne API",
    "DESCRIPTION": "Multi-tenant school CRM API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {
        "EnquiryStatus": "modules.admissions.models.Enquiry.Status",
        "AttendanceStatus": "modules.attendance.models.StudentAttendance.Status",
    },
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env.int("JWT_ACCESS_MINUTES", default=15)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}

REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/0")
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Transactional email (OTP and operational notifications). Production values
# are environment-driven; tests override the delivery boundary directly.
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="CampusOne <no-reply@campusone.local>")
EMAIL_HOST = env("EMAIL_HOST", default="localhost")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=10)

# Azure Blob Storage. Leave the connection string empty when using managed
# identity with AZURE_STORAGE_ACCOUNT_URL in production.
AZURE_STORAGE_ACCOUNT_URL = env("AZURE_STORAGE_ACCOUNT_URL", default="")
AZURE_STORAGE_CONNECTION_STRING = env("AZURE_STORAGE_CONNECTION_STRING", default="")
AZURE_STORAGE_CONTAINER = env("AZURE_STORAGE_CONTAINER", default="campusone-files")
AZURE_STORAGE_SAS_EXPIRY_MINUTES = env.int("AZURE_STORAGE_SAS_EXPIRY_MINUTES", default=15)
AZURE_STORAGE_UPLOAD_EXPIRY_MINUTES = env.int("AZURE_STORAGE_UPLOAD_EXPIRY_MINUTES", default=30)
AZURE_STORAGE_MAX_UPLOAD_BYTES = env.int("AZURE_STORAGE_MAX_UPLOAD_BYTES", default=104857600)
