# Generated by Django 5.2 for CampusOne.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SCREEN_IDS = (
    "H1",
    "BR1",
    "BR2",
    "ST1",
    "ST2",
    "ST3",
    "RP1",
    "RP2",
    "SD1",
    "SD2",
    "SD3",
    "AD1",
    "AD2",
    "AD3",
    "AD4",
    "AD5",
    "AD6",
    "AC1",
    "AC2",
    "AC3",
    "AC4",
    "AC5",
    "AC6",
    "AC7",
    "AT1",
    "AT2",
    "AT3",
    "FN1",
    "FN2",
    "FN3",
    "FN4",
    "CM1",
    "CM2",
    "TT1",
    "TT2",
    "RG1",
    "RG2",
    "RG3",
    "RG4",
    "RG5",
    "RA1",
    "RA2",
    "AO1",
    "AO2",
    "AO3",
    "SE1",
    "SE2",
    "SE3",
    "SE4",
    "SE5",
    "AL1",
    "NT1",
    "PR1",
    "HP1",
)

SCREEN_CHOICES = (
    ("H1", "Dashboard"),
    ("BR1", "Branches List"),
    ("BR2", "Branch Detail"),
    ("ST1", "Staff Directory"),
    ("ST2", "Staff Profile"),
    ("ST3", "Staff Leave Approvals"),
    ("RP1", "Roles List"),
    ("RP2", "Role Builder"),
    ("SD1", "Student Directory"),
    ("SD2", "Student Profile"),
    ("SD3", "Bulk Import & ID Cards"),
    ("AD1", "Admissions Dashboard & Funnel"),
    ("AD2", "Enquiries Inbox"),
    ("AD3", "Enquiry Detail"),
    ("AD4", "Application Form Builder"),
    ("AD5", "Visit & Entrance Test Scheduler"),
    ("AD6", "Counselor Assignment & Workload"),
    ("AC1", "Academic Year & Calendar"),
    ("AC2", "Classes, Sections & Subjects"),
    ("AC3", "Grading Scale Configuration"),
    ("AC4", "Assessments & Exams"),
    ("AC5", "Common Test Builder"),
    ("AC6", "Report Cards"),
    ("AC7", "Syllabus Oversight"),
    ("AT1", "Attendance Dashboard"),
    ("AT2", "Low-Attendance Alerts & Policy"),
    ("AT3", "Staff Attendance"),
    ("FN1", "Fee Structure Builder"),
    ("FN2", "Collection Dashboard & Invoices"),
    ("FN3", "Defaulter Reports"),
    ("FN4", "Refunds & Withdrawals"),
    ("CM1", "Circulars & Broadcast"),
    ("CM2", "Message Templates"),
    ("TT1", "Timetable Builder"),
    ("TT2", "Substitute Management"),
    ("RG1", "Point Categories & Activity Types"),
    ("RG2", "Batch (Badge) Definitions"),
    ("RG3", "Leaderboard Settings"),
    ("RG4", "Institute Leaderboard View"),
    ("RG5", "Cross-Institute Partnerships"),
    ("RA1", "Reports Hub"),
    ("RA2", "Custom Report Builder"),
    ("AO1", "Transport"),
    ("AO2", "Library"),
    ("AO3", "Hostel"),
    ("SE1", "Institute Profile & Branding"),
    ("SE2", "Academic & Regional Configuration"),
    ("SE3", "Subscription & Billing"),
    ("SE4", "Data Privacy & Consent"),
    ("SE5", "Notification Channels"),
    ("AL1", "Audit Log"),
    ("NT1", "Notifications"),
    ("PR1", "My Account"),
    ("HP1", "Help & Support"),
)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institutes", "0002_remove_institutemembership_uq_membership_scope_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("screen_id", models.CharField(choices=SCREEN_CHOICES, max_length=4)),
                ("record_type", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=240)),
                ("status", models.CharField(max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_records",
                        to="institutes.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_admin_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_records",
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "db_table": "admin_records",
                "ordering": ("-updated_at", "-created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["institute", "screen_id", "is_active", "-updated_at"],
                        name="admrec_tenant_screen_idx",
                    ),
                    models.Index(
                        fields=["institute", "branch", "screen_id", "is_active"],
                        name="admrec_branch_screen_idx",
                    ),
                    models.Index(
                        fields=["institute", "screen_id", "status", "is_active"],
                        name="admrec_screen_status_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("screen_id__in", SCREEN_IDS)),
                        name="ck_admrec_valid_screen",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="ck_admrec_version_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("record_type", ""), _negated=True),
                        name="ck_admrec_type_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="ck_admrec_title_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status", ""), _negated=True),
                        name="ck_admrec_status_not_empty",
                    ),
                ],
            },
        ),
    ]

