# Generated by Django 5.2.16 on 2026-07-18 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "institutes",
            "0002_remove_institutemembership_uq_membership_scope_role_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicCalendarEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("EXAM", "Exam"),
                            ("HOLIDAY", "Holiday"),
                            ("PTM", "Parent-teacher meeting"),
                            ("EVENT", "Event"),
                        ],
                        max_length=16,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="institutes.branch",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_on", "title"),
                "indexes": [
                    models.Index(
                        fields=["institute", "starts_on"],
                        name="school_cale_institu_aa28c0_idx",
                    )
                ],
            },
        ),
    ]
