# Generated by Django 5.2.16 on 2026-08-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_calendar", "0002_calendar_integrations"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="calendarintegrationconnection",
            name="institute",
        ),
        migrations.RemoveField(
            model_name="calendaroauthstate",
            name="institute",
        ),
        migrations.RemoveField(
            model_name="calendaroauthstate",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="academiccalendarevent",
            name="uq_calendar_external_event",
        ),
        migrations.RemoveField(
            model_name="academiccalendarevent",
            name="source_event_id",
        ),
        migrations.RemoveField(
            model_name="academiccalendarevent",
            name="source_provider",
        ),
        migrations.DeleteModel(
            name="CalendarIntegrationConnection",
        ),
        migrations.DeleteModel(
            name="CalendarOAuthState",
        ),
    ]

    # The legacy integration tables were removed outside Django on some
    # deployments. Keep the migration state transition, but do not issue
    # DROP/ALTER statements against tables that may already be absent.
    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations)]
