# Generated by Django 5.2.16 on 2026-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_user_otp_required_otpchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
